#!/usr/bin/env python3
"""Produce a compact private preview for a user-supplied PDF in a GitHub runner.
Artifacts generated by this script must be encrypted before any upload."""
import sys, json, pathlib, zipfile, re
import pymupdf as fitz

source=pathlib.Path(sys.argv[1])
destination=pathlib.Path(sys.argv[2])
doc=fitz.open(str(source))
info={
  "pages": len(doc),
  "sizes_pt": [],
  "title": str(doc.metadata.get("title") or "")[:150],
  "per_page": [],
}
positions=list(range(len(doc))) if len(doc)<=60 else sorted(set([0,1,2,3,4,5,*range(6,len(doc),max(1,len(doc)//45)),len(doc)-1]))
positions=[p for p in positions if 0<=p<len(doc)]
text_parts=[]
with zipfile.ZipFile(destination,"w",zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
    for p in positions:
        page=doc[p]
        w,h=page.rect.width,page.rect.height
        pix=page.get_pixmap(matrix=fitz.Matrix(min(620/w,620/h),min(620/w,620/h)),alpha=False,colorspace=fitz.csRGB)
        thumb=pix.tobytes("jpeg",jpg_quality=48)
        archive.writestr(f"page_{p+1:03d}.jpg",thumb)
        text=page.get_text("text")
        info["per_page"].append({"page":p+1,"w":round(w,1),"h":round(h,1),
            "chars":len(text),"image_bytes":len(thumb),"text_excerpt":text[:1300]})
        text_parts.append(f"=== Page {p+1} ===\n"+text[:2000])
    info["pages_with_previews"]=len(positions)
    archive.writestr("summary.json",json.dumps(info,ensure_ascii=False,indent=2))
    archive.writestr("text.txt","\n".join(text_parts))
print(json.dumps(info,ensure_ascii=False))
