#!/usr/bin/env python3
"""Produce a compact private preview for a user-supplied PDF in a GitHub runner.
Artifacts generated by this script must be encrypted before any upload."""
import sys, json, pathlib, zipfile, re
import pymupdf as fitz

source=pathlib.Path(sys.argv[1])
destination=pathlib.Path(sys.argv[2])
doc=fitz.open(str(source))
info={
  "pages": len(doc),
  "sizes_pt": [],
  "title": str(doc.metadata.get("title") or "")[:150],
  "per_page": [],
}
positions=list(range(len(doc))) if len(doc)<=60 else sorted(set([0,1,2,3,4,5,*range(6,len(doc),max(1,len(doc)//45)),len(doc)-1]))
positions=[p for p in positions if 0<=p<len(doc)]
text_parts=[]
with zipfile.ZipFile(destination,"w",zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
    for p in positions:
        page=doc[p]
        w,h=page.rect.width,page.rect.height
        pix=page.get_pixmap(matrix=fitz.Matrix(min(620/w,620/h),min(620/w,620/h)),alpha=False,colorspace=fitz.csRGB)
        thumb=pix.tobytes("jpeg",jpg_quality=48)
        archive.writestr(f"page_{p+1:03d}.jpg",thumb)
        text=page.get_text("text")
        info["per_page"].append({"page":p+1,"w":round(w,1),"h":round(h,1),
            "chars":len(text),"image_bytes":len(thumb),"text_excerpt":text[:1300]})
        text_parts.append(f"=== Page {p+1} ===\n"+text[:2000])
    info["pages_with_previews"]=len(positions)
    archive.writestr("summary.json",json.dumps(info,ensure_ascii=False,indent=2))
    archive.writestr("text.txt","\n".join(text_parts))
    def compressed_subset(label, one_based_pages, max_px=1550, quality=75):
        reduced=fitz.open()
        for pn in one_based_pages:
            if not 1<=pn<=len(doc): continue
            original=doc[pn-1]
            w,h=original.rect.width,original.rect.height
            scale=min(max_px/w,max_px/h)
            pix=original.get_pixmap(matrix=fitz.Matrix(scale,scale),alpha=False,colorspace=fitz.csRGB)
            jpg=pix.tobytes("jpeg",jpg_quality=quality)
            leaf=reduced.new_page(width=w,height=h)
            leaf.insert_image(leaf.rect,stream=jpg)
        payload=reduced.tobytes(garbage=4,deflate=True)
        archive.writestr(label,payload)
        return {"pages":len(one_based_pages),"bytes":len(payload)}
    info["architecture_pdf"]=compressed_subset("Polishko_memorial_concept_FPG.pdf",
        [1,*range(2,13),21,22,23,24],max_px=1500,quality=73)
    info["support_letters_pdf"]=compressed_subset("Polishko_support_letters_FPG.pdf",
        list(range(27,44)),max_px=1500,quality=75)

print(json.dumps(info,ensure_ascii=False))
